// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Only used by CLI commands (migrate/introspect): the app connects via lib/db.ts
    // using DATABASE_URL. Migrations cannot run through Supabase transaction pooling
    // (pgbouncer), so the CLI uses the direct session-mode URL.
    url: process.env["DIRECT_URL"],
  },
});
